const shopsList: any = [
  {
    id: 1,
    name: "Campus Canteen",
    category: "Food",
    description: "Affordable meals and snacks for students.",
    address: "Block A, Near Main Gate",
    contact: "+91 9876543210",
    rating: 4.3,
    openingHours: "8:00 AM - 10:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=1",
    distance: "0.2 km",
    offers: "10% off for students",
  },
  {
    id: 2,
    name: "Techie Stationery",
    category: "Stationery",
    description: "All books, notes, and stationery available.",
    address: "Market Road, Shop 12",
    contact: "+91 9876543211",
    rating: 4.5,
    openingHours: "9:00 AM - 8:00 PM",
    deliveryAvailable: false,
    image: "https://picsum.photos/400/250?random=2",
    distance: "0.5 km",
    offers: "Buy 2 pens get 1 free",
  },
  {
    id: 3,
    name: "Quick Bites",
    category: "Fast Food",
    description: "Burgers, fries, and cold drinks.",
    address: "College Circle",
    contact: "+91 9876543212",
    rating: 4.1,
    openingHours: "10:00 AM - 11:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=3",
    distance: "0.3 km",
    offers: "Free cold drink with burger combo",
  },
  {
    id: 4,
    name: "Book World",
    category: "Bookstore",
    description: "Academic and competitive exam books.",
    address: "Market Street, Shop 7",
    contact: "+91 9876543213",
    rating: 4.7,
    openingHours: "10:00 AM - 9:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=4",
    distance: "0.6 km",
    offers: "15% off on reference books",
  },
  {
    id: 5,
    name: "Laundry Express",
    category: "Laundry",
    description: "Quick and clean laundry services.",
    address: "Behind Hostel B",
    contact: "+91 9876543214",
    rating: 4.0,
    openingHours: "7:00 AM - 9:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=5",
    distance: "0.1 km",
    offers: "Free ironing with wash",
  },
  {
    id: 6,
    name: "Healthy Tiffins",
    category: "Food Delivery",
    description: "Daily meals delivered to hostels.",
    address: "Market Lane, Shop 3",
    contact: "+91 9876543215",
    rating: 4.6,
    openingHours: "6:00 AM - 10:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=6",
    distance: "0.4 km",
    offers: "Weekly plan at discounted price",
  },
  {
    id: 7,
    name: "Sports Hub",
    category: "Sports",
    description: "Cricket, football, and gym equipment.",
    address: "College Market Area",
    contact: "+91 9876543216",
    rating: 4.2,
    openingHours: "9:00 AM - 8:00 PM",
    deliveryAvailable: false,
    image: "https://picsum.photos/400/250?random=7",
    distance: "0.7 km",
    offers: "Flat 5% off on cricket kits",
  },
  {
    id: 8,
    name: "Sweet Treats",
    category: "Bakery",
    description: "Cakes, pastries, and cookies.",
    address: "Opposite Main Gate",
    contact: "+91 9876543217",
    rating: 4.8,
    openingHours: "8:00 AM - 10:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=8",
    distance: "0.25 km",
    offers: "Birthday cake customization",
  },
  {
    id: 9,
    name: "Medic Plus",
    category: "Pharmacy",
    description: "Medicines and health products.",
    address: "Market Road, Shop 18",
    contact: "+91 9876543218",
    rating: 4.4,
    openingHours: "24 Hours",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=9",
    distance: "0.5 km",
    offers: "5% off for students",
  },
  {
    id: 10,
    name: "Cafe Chill",
    category: "Cafe",
    description: "Coffee, tea, and chill vibes.",
    address: "Near Library Gate",
    contact: "+91 9876543219",
    rating: 4.5,
    openingHours: "9:00 AM - 11:00 PM",
    deliveryAvailable: true,
    image: "https://picsum.photos/400/250?random=10",
    distance: "0.35 km",
    offers: "Buy 1 get 1 free coffee on Mondays",
  },
];

export default shopsList;
